### ISSUE TITLE
Rename docker contexts to standardised format

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocurrent-deployer#114]
## Background
The docker contexts used in ocurrent-deployer have mixed naming standards and it's not clear which environment or machine a context is targeting.

## Summary
The docker contexts as used by deployer are a mix of various naming standards. They should be renamed to follow a standardised naming pattern of hostnames. Currently it looks like:

| NAME                 | TYPE | DESCRIPTION                             | DOCKER ENDPOINT                |
|----------------------|------|-----------------------------------------|--------------------------------|
| ci3.ocamllabs.io     | moby | Ci3 - OCamlLabs                         | ssh://root@ci3.ocamllabs.io    |
| ci4                  | moby |                                         | ssh://root@ci4.ocamllabs.io    |
| ci6                  | moby |                                         | ssh://root@ci6.ocamllabs.io    |
| default *            | moby | Current DOCKER_HOST based configuration | unix:///var/run/docker.sock    |
| deploy-ocaml-org     | moby | deploy.ci.ocaml.org                     | ssh://root@deploy.ci.ocaml.org |
| docsci               | moby |                                         | ssh://root@docs.ci.ocaml.org   |
| m1-a                 | moby |                                         | ssh://root@147.75.33.203       |
| ocaml-www1           | moby |                                         | ssh://root@staging.ocaml.org   |
| opam3-ocaml-org      | moby | opam-3.ocaml.org                        | ssh://ubuntu@opam-3.ocaml.org  |
| packet_current_bench | moby |                                         | ssh://root@147.75.32.19        |
| tezos                | moby |                                         | ssh://root@tezos.ci.dev        |
| toxis                | moby |                                         | ssh://root@ci.ocamllabs.io     |
| v2-ocaml-org         | moby | v2.ocaml.org                            | ssh://root@v2.ocaml.org        |
| v3-ocaml-org         | moby | v3.ocaml.org                            | ssh://root@v3.ocaml.org        |

which should change to :

| NAME                | TYPE | DESCRIPTION                 | DOCKER ENDPOINT                |
|---------------------|------|-----------------------------|--------------------------------|
| ci.ocamllabs.io     | moby | Toxis - OCamlLabs           | ssh://root@ci.ocamllabs.io     |
| ci3.ocamllabs.io    | moby | Ci3 - OCamlLabs             | ssh://root@ci3.ocamllabs.io    |
| ci4.ocamllabs.io    | moby | Ci4 - OCamlLabs             | ssh://root@ci4.ocamllabs.io    |
| tezos.ci.dev        | moby | Tezos CI - OCamlLabs        | ssh://root@tezos.ci.dev        |
| deploy.ci.ocaml.org | moby | OCaml - deploy.ci.ocaml.org | ssh://root@deploy.ci.ocaml.org |
| opam-3.ocaml.org    | moby | OPAM - opam-3.ocaml.org     | ssh://root@opam-3.ocaml.org    |
| v2.ocaml.org        | moby | OCaml - v2.ocaml.org        | ssh://root@v2.ocaml.org        |
| v3.ocaml.org        | moby | OCaml - v3.ocaml.org        | ssh://root@v3.ocaml.org        |

## Outcome

As a result of this work the docker contexts used in deployer should be changed to the new names and the different ocurrent-deployer flavours are updated.

**Comment by mtelvers** [comment]
In normal operation, the context `deploy.ci.ocaml.org` would be unused as the deployer would be using the default context on that machine.

**Comment by mtelvers** [comment]
`docsci` appears to still be in use.  I will rename that `docs.ci.ocaml.org`.

**Comment by mtelvers** [comment]
All the contexts have now been renamed.
