### ISSUE TITLE
Link on github ci doesn't point to deployer web ui

### ISSUE THREAD

**Issue by MisterDA** [ocurrent/ocurrent-deployer#127]
I see `View more details on deploy.ci3.ocamllabs.io` but it links to <https://github.com/ocurrent/ocurrent-deployer>.

**Comment by MisterDA** [comment]
> It would be even nicer if, instead of deleting the unused index, we could use the index to provide useful links from GitHub. At the moment, there's no suitable landing page to link to, however, and it might not be worth it.


_Originally posted by @talex5 in https://github.com/ocurrent/ocurrent-deployer/pull/128#pullrequestreview-1041646469_

**Comment by tmcgilchrist** [comment]
The issue with linking back to the application rather than the git repo has been fixed.
