### ISSUE TITLE
The link in the checks page doesn't work

### ISSUE THREAD

**Issue by talex5** [ocurrent/ocurrent-deployer#68]
We switched from using statuses to using GitHub checks in #65. But the link there ("View more details on ci3.ocamllabs.io deployer") instead goes to https://github.com/ocurrent/ocurrent-deployer, which isn't very useful.

/cc @tmcgilchrist

**Comment by tmcgilchrist** [comment]
Minor json change here should fix it. https://github.com/ocurrent/ocurrent/pull/282

**Comment by tmcgilchrist** [comment]
https://github.com/ocurrent/ocurrent-deployer/pull/72
